{
 "title": "New dashboard",
 "time": { "from": "2025-09-07T16:38:41.838Z", "to": "2025-09-07T16:43:02.227Z" },
 "panels": [
  {
   "title": "Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, timestamp FROM dummy_metrics "
    }
   ]
  },
  {
   "title": "Number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, timestamp FROM dummy_metrics "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, timestamp FROM dummy_metrics "
    }
   ]
  }
 ]
}