services: 
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=ride_predictions
      - TEST_RUN=True
      - MODEL_LOCATION=/app/model
      - RUN_ID=Test123
    volumes:
      - "./model:/app/model"






